name: CI

on:
  push:
  pull_request:

permissions:
  contents: write


jobs:
  verify-build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
      
      - name: Install
        run: yarn install

      - name: Lint
        run: |
          yarn lint:js
          yarn lint:md
          yarn lint:scss

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build


      - name: Create dist.zip
        run: zip -qq -r dist.zip dist/

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist.zip
          path: dist.zip
          if-no-files-found: error

      - name: Upload release assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist.zip

